// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookController from "./book_controller"
application.register("book", BookController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)

import SpeechController from "./speech_controller"
application.register("speech", SpeechController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)
