# Generated by Django 6.0.3 on 2026-03-18 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcards', to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=8)),
                ('back_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=8)),
                ('front_data', models.JSONField()),
                ('back_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_flashcards', to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=8)),
                ('back_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=8)),
                ('front_data', models.JSONField()),
                ('back_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='book.bookcard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookcard',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='uniq_bookcard_user_book'),
        ),
        migrations.AddConstraint(
            model_name='defaultflashcard',
            constraint=models.CheckConstraint(condition=models.Q(('front_language', models.F('back_language')), _negated=True), name='default_flashcard_front_back_language_different'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.CheckConstraint(condition=models.Q(('front_language', models.F('back_language')), _negated=True), name='flashcard_front_back_language_different'),
        ),
    ]
