# Generated by Django 6.0.3 on 2026-04-03 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_ingestionjob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookcard',
            name='uniq_bookcard_user_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
        migrations.AddField(
            model_name='book',
            name='identifier',
            field=models.CharField(db_index=True, default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookcard',
            name='author',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bookcard',
            name='epub_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bookcard',
            name='title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookcards', to='book.book'),
        ),
    ]
