# Generated by Django 6.0.3 on 2026-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_bookcard_uniq_bookcard_user_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='card_count_target',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='rarity_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
